version: '3'
services:
  db:
    image: postgres:15.3
    volumes:
      - ./aquacol_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=AquacolData
    ports:
      - "5434:5432"

  app:
    build: ./app
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=AquacolData
    ports:
      - "8009:8009"
    depends_on:
      - db
    command: ["./app/wait_for_it.sh", "db:5434", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8009"]

volumes:
  aquacol_postgres_data:
    external: true