version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./aquacol_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=AquacolData
    ports:
      - "5434:5432"

  app:
    build: ./app
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=AquacolData
    ports:
      - "8009:8009"
    depends_on:
      - db

volumes:
  aquacol_postgres_data:
    external: true